# Transformer Model Training

This notebook loads the processed transformer inputs created in "pre-process.ipynb" and prepares them for model training.

In [1]:
import numpy as np
import pandas as pd

## Load saved transformer arrays

In [2]:
epochs = 8
batch_size = 8

# SET EXPERIMENT TYPE TO RUN THE CODE ["baseline", "customer-only", "metadata-prefix", "customer-only-386", "customer-only-low-lr", ]
experiment_type = "customer-only-low-lr"

if experiment_type == "baseline":
    learning_rate = 2e-5

    X_train_input_ids = np.load("X_train_input_ids.npy")
    X_train_attention_mask = np.load("X_train_attention_mask.npy")

    X_val_input_ids = np.load("X_val_input_ids.npy")
    X_val_attention_mask = np.load("X_val_attention_mask.npy")

    X_test_input_ids = np.load("X_test_input_ids.npy")
    X_test_attention_mask = np.load("X_test_attention_mask.npy")

    y_train = np.load("y_train.npy")
    y_val = np.load("y_val.npy")
    y_test = np.load("y_test.npy")

    # set experiment name for wb
    experiment_name = "distilbert-transformer-baseline"

    # save best model
    best_model_path = "best_distilbert_model_baseline.pt"

elif experiment_type == "customer-only": # It has max length --> 512
    learning_rate = 2e-5

    X_train_input_ids = np.load("X_train_input_ids_customer_only.npy")
    X_train_attention_mask = np.load("X_train_attention_mask_customer_only.npy")

    X_val_input_ids = np.load("X_val_input_ids_customer_only.npy")
    X_val_attention_mask = np.load("X_val_attention_mask_customer_only.npy")

    X_test_input_ids = np.load("X_test_input_ids_customer_only.npy")
    X_test_attention_mask = np.load("X_test_attention_mask_customer_only.npy")

    y_train = np.load("y_train_customer_only.npy")
    y_val = np.load("y_val_customer_only.npy")
    y_test = np.load("y_test_customer_only.npy")

    # set experiment name for wb
    experiment_name = "distilbert-transformer-customer-only_512"

    # save best model
    best_model_path = "best_distilbert_model_customer_only.pt"

elif experiment_type == "metadata-prefix":
    learning_rate = 2e-5

    X_train_input_ids = np.load("X_train_input_ids_metadata_prefix.npy")
    X_train_attention_mask = np.load("X_train_attention_mask_metadata_prefix.npy")

    X_val_input_ids = np.load("X_val_input_ids_metadata_prefix.npy")
    X_val_attention_mask = np.load("X_val_attention_mask_metadata_prefix.npy")

    X_test_input_ids = np.load("X_test_input_ids_metadata_prefix.npy")
    X_test_attention_mask = np.load("X_test_attention_mask_metadata_prefix.npy")

    y_train = np.load("y_train_metadata_prefix.npy")
    y_val = np.load("y_val_metadata_prefix.npy")
    y_test = np.load("y_test_metadata_prefix.npy")

    # set experiment name for wb
    experiment_name = "distilbert-transformer-metadata-prefix"

    # save best model
    best_model_path = "best_distilbert_model_metadata_prefix.pt"

elif experiment_type == "customer-only-386": # 386 is max length
    learning_rate = 2e-5

    X_train_input_ids = np.load("X_train_input_ids_customer_only_386.npy")
    X_train_attention_mask = np.load("X_train_attention_mask_customer_only_386.npy")

    X_val_input_ids = np.load("X_val_input_ids_customer_only_386.npy")
    X_val_attention_mask = np.load("X_val_attention_mask_customer_only_386.npy")

    X_test_input_ids = np.load("X_test_input_ids_customer_only_386.npy")
    X_test_attention_mask = np.load("X_test_attention_mask_customer_only_386.npy")

    y_train = np.load("y_train_customer_only_386.npy")
    y_val = np.load("y_val_customer_only_386.npy")
    y_test = np.load("y_test_customer_only_386.npy")

    # set experiment name for wb
    experiment_name = "distilbert-transformer-customer-only_386"

    # save best model
    best_model_path = "best_distilbert_model_customer_only_386.pt"

elif experiment_type == "customer-only-low-lr":
    learning_rate = 1e-5 # Use low learning rate with customer only text and 512 max length

    X_train_input_ids = np.load("X_train_input_ids_customer_only.npy")
    X_train_attention_mask = np.load("X_train_attention_mask_customer_only.npy")

    X_val_input_ids = np.load("X_val_input_ids_customer_only.npy")
    X_val_attention_mask = np.load("X_val_attention_mask_customer_only.npy")

    X_test_input_ids = np.load("X_test_input_ids_customer_only.npy")
    X_test_attention_mask = np.load("X_test_attention_mask_customer_only.npy")

    y_train = np.load("y_train_customer_only.npy")
    y_val = np.load("y_val_customer_only.npy")
    y_test = np.load("y_test_customer_only.npy")

    # set experiment name for wb
    experiment_name = "distilbert-transformer-customer-only_low_lr"

    # save best model
    best_model_path = "best_distilbert_model_customer_only_low_lr.pt"

In [3]:
X_train_input_ids

array([[ 101, 7632, 4532, ...,    0,    0,    0],
       [ 101, 7632, 1010, ...,    0,    0,    0],
       [ 101, 7632, 3419, ..., 2017, 1005,  102],
       ...,
       [ 101, 7632, 1010, ...,    0,    0,    0],
       [ 101, 7632, 5586, ...,    0,    0,    0],
       [ 101, 7632, 1010, ...,    0,    0,    0]], shape=(774, 386))

In [4]:
X_train_attention_mask

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], shape=(774, 386))

In [5]:
y_train

array([1, 1, 1, 0, 1, 2, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 2, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       2, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 2, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 2, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 2, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 2, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 2, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 2, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 2, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 2, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 2, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 2, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1])

In [6]:
print("X_train_input_ids shape:", X_train_input_ids.shape)
print("X_train_attention_mask shape:", X_train_attention_mask.shape)
print("X_val_input_ids shape:", X_val_input_ids.shape)
print("X_val_attention_mask shape:", X_val_attention_mask.shape)
print("X_test_input_ids shape:", X_test_input_ids.shape)
print("X_test_attention_mask shape:", X_test_attention_mask.shape)

print("y_train shape:", y_train.shape)
print("y_val shape:", y_val.shape)
print("y_test shape:", y_test.shape)

X_train_input_ids shape: (774, 386)
X_train_attention_mask shape: (774, 386)
X_val_input_ids shape: (194, 386)
X_val_attention_mask shape: (194, 386)
X_test_input_ids shape: (30, 386)
X_test_attention_mask shape: (30, 386)
y_train shape: (774,)
y_val shape: (194,)
y_test shape: (30,)

In [7]:
print("Train label counts:")
print(pd.Series(y_train).value_counts().sort_index())

print("\nValidation label counts:")
print(pd.Series(y_val).value_counts().sort_index())

print("\nTest label counts:")
print(pd.Series(y_test).value_counts().sort_index())

Train label counts:
0    327
1    433
2     14
Name: count, dtype: int64

Validation label counts:
0     82
1    109
2      3
Name: count, dtype: int64

Test label counts:
0    10
1    10
2    10
Name: count, dtype: int64

## DistilBERT classifier

Use a pretrained DistilBERT model for 3-class sentiment classification and fine-tune it.

The model used in the training notebook is: DistilBertForSequenceClassification --> This is a DistilBERT model with a classification head added on top for sentiment prediction.


Why DistilBERT?

DistilBERT is an encoder-only transformer. For text classification, it reads the whole input sequence, builds contextual representations, and then uses a classification head on top to predict the label.

DistilBERT is a smaller, faster version of BERT. It is a pretrained transformer model that understands language context and can be fine-tuned for classification tasks such as sentiment analysis.

So, DistilBERT:
- sentiment is mainly expressed in the conversation text
- captures contextual meaning better than traditional models
- is lighter and faster than full BERT
- the dataset is relatively small, use pretrained model for it


Alternatives to DistilBERT:

- BERT-base-uncased: Stronger than DistilBERT, but heavier and slower.
- RoBERTa-base: Often performs very well on classification tasks, but is also heavier than DistilBERT.
- ALBERT: Smaller and more parameter-efficient, but sometimes less straightforward to fine-tune.
- DeBERTa-v3-base: Very strong for classification, but heavier and more demanding.
- MiniLM: Smaller and faster than DistilBERT, good if resources are limited.

So, they can be heavy for this simple task.

- I'll keep DistilBERT as the main model --> baseline model
- MAYBE BERT or RoBERTa can be alternatives. If needed, we can compare with the baseline but

In [8]:
import torch
from torch.optim import AdamW
from torch.utils.data import Dataset, DataLoader
from transformers import DistilBertForSequenceClassification, get_linear_schedule_with_warmup # from Hugging Face
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, classification_report

/Users/fatmaoztel/Desktop/Fatima Projects/cs-conversation-sentiment-analysis/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [9]:
if torch.backends.mps.is_available():
    device = torch.device("mps")
elif torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

print("Using device:", device) ## Because my device is Apple M1 with 16 GB memory

Using device: mps

I use the same DistilBERT checkpoint as in preprocessing so the tokenization and model vocabulary remain aligned.

In [10]:
model_checkpoint = "distilbert-base-uncased"
num_labels = 3

model = DistilBertForSequenceClassification.from_pretrained(
    model_checkpoint,
    num_labels=num_labels
)
model.to(device)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 100/100 [00:00<00:00, 7225.33it/s]
DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=3, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

* distilbert = the model family
* base = the standard-size version
* uncased = text is handled in lowercase form

Model:
* load pretrained weights from distilbert-base-uncased
* attach a classification layer
* set the output to 3 classes
* model_checkpoint = the pretrained model name
* DistilBertForSequenceClassification = the actual classification model class used for training

#### SET W&B Connection

In [11]:
import wandb
wandb.login()

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /Users/fatmaoztel/.netrc.
wandb: Currently logged in as: ftmoztl to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

True

Weights & Biases is initialized

### Datasets and dataloaders (For PyTorch)

In [12]:
class SentimentDataset(Dataset):
    def __init__(self, input_ids, attention_mask, labels):
        self.input_ids = torch.tensor(input_ids, dtype=torch.long)
        self.attention_mask = torch.tensor(attention_mask, dtype=torch.long)
        self.labels = torch.tensor(labels, dtype=torch.long)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {
            "input_ids": self.input_ids[idx],
            "attention_mask": self.attention_mask[idx],
            "labels": self.labels[idx]
        }

In [13]:
train_dataset = SentimentDataset(X_train_input_ids, X_train_attention_mask, y_train)
val_dataset = SentimentDataset(X_val_input_ids, X_val_attention_mask, y_val)
test_dataset = SentimentDataset(X_test_input_ids, X_test_attention_mask, y_test)

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

print("Train batches:", len(train_loader))
print("Validation batches:", len(val_loader))
print("Test batches:", len(test_loader))

Train batches: 97
Validation batches: 25
Test batches: 4

A small batch size is used because transformer models require substantial memory.

### Optimizer and scheduler

In [14]:
optimizer = AdamW(model.parameters(), lr=learning_rate)
total_steps = len(train_loader) * epochs

scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=0,
    num_training_steps=total_steps
)

A low learning rate is chosen because we are fine-tuning a pretrained model rather than training a new model from scratch.
This is a common small learning rate for transformer fine-tuning.

Don't forget, scheduler makes LR like:  current_lr = initial_lr * (1 - step / total_steps)

Means that: learning rate is not fixed by epoch, it decreases every batch

IMPORTANT NOTE: Because DistilBERT is a pretrained transformer rather than a randomly initialized model, only a small number of epochs is typically required for fine-tuning. Given the relatively small dataset size, training for too many epochs would likely cause overfitting rather than improved generalization.

In [15]:
wandb.init(
    project="cs-conversation-sentiment-analysis",
    name=experiment_name,
    config={
        "model_checkpoint": model_checkpoint,
        "num_labels": num_labels,
        "batch_size": batch_size,
        "epochs": epochs,
        "learning_rate": learning_rate,
        "device": str(device),
        "train_size": len(train_dataset),
        "val_size": len(val_dataset),
        "test_size": len(test_dataset)
    }
)

wandb: setting up run w1iwtnwf
wandb: Tracking run with wandb version 0.25.1
wandb: Run data is saved locally in /Users/fatmaoztel/Desktop/Fatima Projects/cs-conversation-sentiment-analysis/analysis/wandb/run-20260315_212732-w1iwtnwf
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run distilbert-transformer-customer-only_low_lr
wandb: ⭐️ View project at https://wandb.ai/ftmoztl/cs-conversation-sentiment-analysis
wandb: 🚀 View run at https://wandb.ai/ftmoztl/cs-conversation-sentiment-analysis/runs/w1iwtnwf

### Handle class imbalance with weighted loss

In [16]:
class_counts = np.bincount(y_train) #counts how many samples belong to each class in the training set
class_weights = len(y_train) / (len(class_counts) * class_counts)
class_weights = torch.tensor(class_weights, dtype=torch.float).to(device)

loss_fn = torch.nn.CrossEntropyLoss(weight=class_weights)

print("Class counts:", class_counts)
print("Class weights:", class_weights)

Class counts: [327 433  14]
Class weights: tensor([ 0.7890,  0.5958, 18.4286], device='mps:0')

Weighted loss is used because the classes are imbalanced, especially the positive class.

### Training and evaluation functions

In [17]:
def train_one_epoch(model, data_loader, optimizer, scheduler, device, loss_fn):
    model.train()
    total_loss = 0

    for batch in data_loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["labels"].to(device)

        optimizer.zero_grad()
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        logits = outputs.logits
        loss = loss_fn(logits, labels)

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        scheduler.step()

        total_loss += loss.item()

    return total_loss / len(data_loader)

In [18]:
def evaluate_model(model, data_loader, device, loss_fn):
    model.eval()
    total_loss = 0
    all_preds = []
    all_labels = []

    with torch.no_grad():
        for batch in data_loader:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            logits = outputs.logits
            loss = loss_fn(logits, labels)

            total_loss += loss.item()
            preds = torch.argmax(logits, dim=1)

            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    avg_loss = total_loss / len(data_loader)
    accuracy = accuracy_score(all_labels, all_preds)
    precision, recall, f1, _ = precision_recall_fscore_support(
        all_labels,
        all_preds,
        average="macro",
        zero_division=0
    )

    return avg_loss, accuracy, precision, recall, f1, all_labels, all_preds

### Train the model

In [19]:
history = []
best_val_f1 = 0

for epoch in range(epochs):
    train_loss = train_one_epoch(model, train_loader, optimizer, scheduler, device, loss_fn)
    val_loss, val_acc, val_precision, val_recall, val_f1, _, _ = evaluate_model(model, val_loader, device, loss_fn)

    history.append({
        "epoch": epoch + 1,
        "train_loss": train_loss,
        "val_loss": val_loss,
        "val_accuracy": val_acc,
        "val_precision_macro": val_precision,
        "val_recall_macro": val_recall,
        "val_f1_macro": val_f1
    })

    print(f"Epoch {epoch + 1}/{epochs}")
    print(f"  Train loss: {train_loss:.4f}")
    print(f"  Val loss: {val_loss:.4f}")
    print(f"  Val accuracy: {val_acc:.4f}")
    print(f"  Val macro F1: {val_f1:.4f}")

    wandb.log({
        "epoch": epoch + 1,
        "train_loss": train_loss,
        "val_loss": val_loss,
        "val_accuracy": val_acc,
        "val_precision_macro": val_precision,
        "val_recall_macro": val_recall,
        "val_f1_macro": val_f1
    })

    if val_f1 > best_val_f1:
        best_val_f1 = val_f1
        torch.save(model.state_dict(), best_model_path)
        wandb.run.summary["best_val_f1"] = best_val_f1
        print("  Best model updated and saved.")

Epoch 1/8
  Train loss: 0.8834
  Val loss: 0.7167
  Val accuracy: 0.7887
  Val macro F1: 0.5212
  Best model updated and saved.
Epoch 2/8
  Train loss: 0.5951
  Val loss: 0.5562
  Val accuracy: 0.8660
  Val macro F1: 0.5816
  Best model updated and saved.
Epoch 3/8
  Train loss: 0.4860
  Val loss: 0.5951
  Val accuracy: 0.8918
  Val macro F1: 0.5972
  Best model updated and saved.
Epoch 4/8
  Train loss: 0.4275
  Val loss: 0.6154
  Val accuracy: 0.9072
  Val macro F1: 0.6087
  Best model updated and saved.
Epoch 5/8
  Train loss: 0.4164
  Val loss: 0.6591
  Val accuracy: 0.8918
  Val macro F1: 0.5982
Epoch 6/8
  Train loss: 0.3675
  Val loss: 0.7183
  Val accuracy: 0.9021
  Val macro F1: 0.6046
Epoch 7/8
  Train loss: 0.3476
  Val loss: 0.7027
  Val accuracy: 0.9072
  Val macro F1: 0.6085
Epoch 8/8
  Train loss: 0.3558
  Val loss: 0.7187
  Val accuracy: 0.9124
  Val macro F1: 0.6120
  Best model updated and saved.

In [20]:
history_df = pd.DataFrame(history)
display(history_df)

,epoch,train_loss,val_loss,val_accuracy,val_precision_macro,val_recall_macro,val_f1_macro
0,1,0.883390,0.716698,0.788660,0.540133,0.520251,0.521223
1,2,0.595065,0.556199,0.865979,0.576032,0.590289,0.581587
2,3,0.486049,0.595150,0.891753,0.603994,0.596517,0.597150
3,4,0.427523,0.615414,0.907216,0.607985,0.610726,0.608671
4,5,0.416382,0.659130,0.891753,0.595322,0.601551,0.598239
5,6,0.367510,0.718286,0.902062,0.609062,0.604647,0.604618
6,7,0.347592,0.702673,0.907216,0.609673,0.609719,0.608504
7,8,0.355774,0.718722,0.912371,0.614264,0.612777,0.612007

The best model is selected based on validation macro F1, which is a better metric than accuracy for imbalanced classification.
b

### Evaluate the best model

* Accuracy shows the overall proportion of correct predictions. BUT accuracy alone is not enough for this dataset because the classes are imbalanced.
* Precision measures how many predicted samples of a class are actually correct.
* Recall measures how many real samples of a class the model successfully finds.
* F1 combines precision and recall into one score.
* Use macro metrics in this evaluation. Macro means the metric is calculated separately for each class. Then the class-level scores are averaged equally.This gives negative, neutral, and positive the same importance.

Use Macro Precision, Macro Recall, and Macro F1 because the positive class is very small. Macro metrics prevent the model from looking good only because it performs well on the larger classes.

I choose the best model by Macro F1 because it balances precision and recall.

It is more suitable than accuracy for imbalanced multi-class classification.

It helps ensure that all sentiment classes are considered during model selection.

In [21]:
best_model = DistilBertForSequenceClassification.from_pretrained(model_checkpoint, num_labels=num_labels)
best_model.load_state_dict(torch.load(best_model_path, map_location=device))
best_model.to(device)

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 8049.56it/s]
DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=3, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [22]:
val_loss, val_acc, val_precision, val_recall, val_f1, val_labels, val_preds = evaluate_model(best_model, val_loader, device, loss_fn)
test_loss, test_acc, test_precision, test_recall, test_f1, test_labels, test_preds = evaluate_model(best_model, test_loader, device, loss_fn)

print("Validation metrics")
print(f"Loss: {val_loss:.4f}")
print(f"Accuracy: {val_acc:.4f}")
print(f"Macro Precision: {val_precision:.4f}")
print(f"Macro Recall: {val_recall:.4f}")
print(f"Macro F1: {val_f1:.4f}")

print("\nTest metrics")
print(f"Loss: {test_loss:.4f}")
print(f"Accuracy: {test_acc:.4f}")
print(f"Macro Precision: {test_precision:.4f}")
print(f"Macro Recall: {test_recall:.4f}")
print(f"Macro F1: {test_f1:.4f}")

wandb.log({
    "final_val_loss": val_loss,
    "final_val_accuracy": val_acc,
    "final_val_precision_macro": val_precision,
    "final_val_recall_macro": val_recall,
    "final_val_f1_macro": val_f1,
    "test_loss": test_loss,
    "test_accuracy": test_acc,
    "test_precision_macro": test_precision,
    "test_recall_macro": test_recall,
    "test_f1_macro": test_f1
})

Validation metrics
Loss: 0.7187
Accuracy: 0.9124
Macro Precision: 0.6143
Macro Recall: 0.6128
Macro F1: 0.6120

Test metrics
Loss: 2.5823
Accuracy: 0.5000
Macro Precision: 0.4161
Macro Recall: 0.5000
Macro F1: 0.4171

In [23]:
label_names = ["negative", "neutral", "positive"]

print("Validation classification report:")
print(classification_report(val_labels, val_preds, target_names=label_names, zero_division=0))

print("Test classification report:")
print(classification_report(test_labels, test_preds, target_names=label_names, zero_division=0))

Validation classification report:
              precision    recall  f1-score   support

    negative       0.96      0.87      0.91        82
     neutral       0.88      0.97      0.93       109
    positive       0.00      0.00      0.00         3

    accuracy                           0.91       194
   macro avg       0.61      0.61      0.61       194
weighted avg       0.90      0.91      0.90       194

Test classification report:
              precision    recall  f1-score   support

    negative       0.86      0.60      0.71        10
     neutral       0.39      0.90      0.55        10
    positive       0.00      0.00      0.00        10

    accuracy                           0.50        30
   macro avg       0.42      0.50      0.42        30
weighted avg       0.42      0.50      0.42        30

At this point, the DistilBERT training pipeline is complete.

In [24]:
wandb.finish()

wandb: updating run metadata
wandb: uploading wandb-summary.json; uploading config.yaml
wandb: uploading history steps 8-8, summary
wandb:
wandb: Run history:
wandb:                     epoch ▁▂▃▄▅▆▇█
wandb:        final_val_accuracy ▁
wandb:        final_val_f1_macro ▁
wandb:            final_val_loss ▁
wandb: final_val_precision_macro ▁
wandb:    final_val_recall_macro ▁
wandb:             test_accuracy ▁
wandb:             test_f1_macro ▁
wandb:                 test_loss ▁
wandb:      test_precision_macro ▁
wandb:                        +7 ...
wandb:
wandb: Run summary:
wandb:               best_val_f1 0.61201
wandb:                     epoch 8
wandb:        final_val_accuracy 0.91237
wandb:        final_val_f1_macro 0.61201
wandb:            final_val_loss 0.71872
wandb: final_val_precision_macro 0.61426
wandb:    final_val_recall_macro 0.61278
wandb:             test_accuracy 0.5
wandb:             test_f1_macro 0.41711
wandb:                 test_loss 2.58233
wandb:                        +8 ...
wandb:
wandb: 🚀 View run distilbert-transformer-customer-only_low_lr at: https://wandb.ai/ftmoztl/cs-conversation-sentiment-analysis/runs/w1iwtnwf
wandb: ⭐️ View project at: https://wandb.ai/ftmoztl/cs-conversation-sentiment-analysis
wandb: Synced 4 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20260315_212732-w1iwtnwf/logs

## Test sample analysis

This section attaches the predictions to the original test conversations so the model results can be examined sample by sample.

In [25]:
test_raw_df = pd.read_csv("test.csv").copy()

id_to_label = {0: "negative", 1: "neutral", 2: "positive"}

test_results_df = test_raw_df.copy()
test_results_df["true_label_id"] = y_test
test_results_df["predicted_label_id"] = test_preds
test_results_df["true_label"] = test_results_df["true_label_id"].map(id_to_label)
test_results_df["predicted_label"] = test_results_df["predicted_label_id"].map(id_to_label)
test_results_df["is_correct"] = test_results_df["true_label_id"] == test_results_df["predicted_label_id"]

display(test_results_df[["conversation", "true_label", "predicted_label", "is_correct"]].head())

,conversation,true_label,predicted_label,is_correct
0,Agent: Thank you for calling BrownBox Customer...,negative,neutral,False
1,Agent: Thank you for calling BrownBox Customer...,negative,neutral,False
2,Agent: Thank you for calling BrownBox Customer...,negative,negative,True
3,Agent: Thank you for calling BrownBox Customer...,negative,negative,True
4,Agent: Thank you for calling BrownBox Customer...,negative,neutral,False

### Full test prediction table

In [26]:
display(test_results_df[["issue_area", "issue_category", "true_label", "predicted_label", "is_correct", "conversation"]])

,issue_area,issue_category,true_label,predicted_label,is_correct,conversation
0,Shopping,Pricing and Discounts,negative,neutral,False,Agent: Thank you for calling BrownBox Customer...
1,Login and Account,Account Reactivation and Deactivation,negative,neutral,False,Agent: Thank you for calling BrownBox Customer...
2,Cancellations and returns,Cash on Delivery (CoD) Refunds,negative,negative,True,Agent: Thank you for calling BrownBox Customer...
3,Order,Order Delivery Issues,negative,negative,True,Agent: Thank you for calling BrownBox Customer...
4,Cancellations and returns,Pickup and Shipping,negative,neutral,False,Agent: Thank you for calling BrownBox Customer...
5,Cancellations and returns,Return and Exchange,negative,negative,True,Agent: Thank you for calling BrownBox Customer...
6,Cancellations and returns,Cash on Delivery (CoD) Refunds,negative,negative,True,Agent: Thank you for calling BrownBox Customer...
7,Cancellations and returns,Cash on Delivery (CoD) Refunds,negative,negative,True,Agent: Thank you for calling BrownBox Customer...
8,Shipping,Standard Shipping Speeds and Delivery Charges,negative,negative,True,"Agent: Hello, thank you for contacting BrownBo..."
9,Cancellations and returns,Return and Exchange,negative,neutral,False,Agent: Thank you for calling BrownBox Customer...
10,Shopping,Product Availability and Status,neutral,neutral,True,"Customer: Hello, I was looking to buy a vacuum..."
11,Login and Account,Account Reactivation and Deactivation,neutral,negative,False,Agent: Thank you for calling BrownBox Customer...
12,Shopping,Pricing and Discounts,neutral,neutral,True,Agent: Thank you for calling BrownBox Customer...
13,Shipping,Shipping Options for Returns,neutral,neutral,True,Agent: Thank you for contacting BrownBox custo...
14,Cancellations and returns,Return Checks and Fees,neutral,neutral,True,"Customer: Hi, I have a question about return c..."
15,Warranty,Accessing Warranty Details,neutral,neutral,True,"Agent: Hello, thank you for calling BrownBox C..."
16,Cancellations and returns,Replacement and Return Process,neutral,neutral,True,Agent: Thank you for reaching out to BrownBox ...
17,Warranty,Lost or Missing Warranty Card,neutral,neutral,True,"Agent: Hello, thank you for calling BrownBox c..."
18,Cancellations and returns,Return and Exchange,neutral,neutral,True,Agent: Thank you for calling BrownBox Customer...
19,Order,Order Confirmation and Status,neutral,neutral,True,Agent: Thank you for contacting BrownBox custo...
20,Order,Order Confirmation and Status,positive,neutral,False,Agent: Thank you for calling BrownBox Customer...
21,Order,Order Confirmation and Status,positive,neutral,False,Agent: Thank you for calling BrownBox Customer...
22,Order,Placing an Order,positive,neutral,False,Agent: Thank you for calling BrownBox customer...
23,Order,Placing an Order,positive,neutral,False,Agent: Thank you for calling BrownBox Customer...
24,Order,Order Confirmation and Status,positive,neutral,False,"Customer: Hi, I placed an order for a vacuum c..."
25,Order,Order Confirmation and Status,positive,neutral,False,"Customer: Hi, I'm calling to inquire about my ..."
26,Order,Placing an Order,positive,neutral,False,Agent: Thank you for calling BrownBox Customer...
27,Order,Product Information and Tags,positive,neutral,False,"Customer: Hi there, I'm interested in purchasi..."
28,Order,Order Confirmation and Status,positive,neutral,False,Agent: Thank you for calling BrownBox Customer...
29,Order,Product Information and Tags,positive,neutral,False,Agent: Thank you for calling BrownBox Customer...

### Misclassified samples

In [27]:
misclassified_df = test_results_df[~test_results_df["is_correct"]].copy()
print("Number of misclassified test samples:", len(misclassified_df))
display(misclassified_df[["issue_area", "issue_category", "true_label", "predicted_label", "conversation"]])

Number of misclassified test samples: 15

,issue_area,issue_category,true_label,predicted_label,conversation
0,Shopping,Pricing and Discounts,negative,neutral,Agent: Thank you for calling BrownBox Customer...
1,Login and Account,Account Reactivation and Deactivation,negative,neutral,Agent: Thank you for calling BrownBox Customer...
4,Cancellations and returns,Pickup and Shipping,negative,neutral,Agent: Thank you for calling BrownBox Customer...
9,Cancellations and returns,Return and Exchange,negative,neutral,Agent: Thank you for calling BrownBox Customer...
11,Login and Account,Account Reactivation and Deactivation,neutral,negative,Agent: Thank you for calling BrownBox Customer...
20,Order,Order Confirmation and Status,positive,neutral,Agent: Thank you for calling BrownBox Customer...
21,Order,Order Confirmation and Status,positive,neutral,Agent: Thank you for calling BrownBox Customer...
22,Order,Placing an Order,positive,neutral,Agent: Thank you for calling BrownBox customer...
23,Order,Placing an Order,positive,neutral,Agent: Thank you for calling BrownBox Customer...
24,Order,Order Confirmation and Status,positive,neutral,"Customer: Hi, I placed an order for a vacuum c..."
25,Order,Order Confirmation and Status,positive,neutral,"Customer: Hi, I'm calling to inquire about my ..."
26,Order,Placing an Order,positive,neutral,Agent: Thank you for calling BrownBox Customer...
27,Order,Product Information and Tags,positive,neutral,"Customer: Hi there, I'm interested in purchasi..."
28,Order,Order Confirmation and Status,positive,neutral,Agent: Thank you for calling BrownBox Customer...
29,Order,Product Information and Tags,positive,neutral,Agent: Thank you for calling BrownBox Customer...

### Correctly classified samples

In [28]:
correct_df = test_results_df[test_results_df["is_correct"]].copy()
print("Number of correctly classified test samples:", len(correct_df))
display(correct_df[["issue_area", "issue_category", "true_label", "predicted_label", "conversation"]])

Number of correctly classified test samples: 15

,issue_area,issue_category,true_label,predicted_label,conversation
2,Cancellations and returns,Cash on Delivery (CoD) Refunds,negative,negative,Agent: Thank you for calling BrownBox Customer...
3,Order,Order Delivery Issues,negative,negative,Agent: Thank you for calling BrownBox Customer...
5,Cancellations and returns,Return and Exchange,negative,negative,Agent: Thank you for calling BrownBox Customer...
6,Cancellations and returns,Cash on Delivery (CoD) Refunds,negative,negative,Agent: Thank you for calling BrownBox Customer...
7,Cancellations and returns,Cash on Delivery (CoD) Refunds,negative,negative,Agent: Thank you for calling BrownBox Customer...
8,Shipping,Standard Shipping Speeds and Delivery Charges,negative,negative,"Agent: Hello, thank you for contacting BrownBo..."
10,Shopping,Product Availability and Status,neutral,neutral,"Customer: Hello, I was looking to buy a vacuum..."
12,Shopping,Pricing and Discounts,neutral,neutral,Agent: Thank you for calling BrownBox Customer...
13,Shipping,Shipping Options for Returns,neutral,neutral,Agent: Thank you for contacting BrownBox custo...
14,Cancellations and returns,Return Checks and Fees,neutral,neutral,"Customer: Hi, I have a question about return c..."
15,Warranty,Accessing Warranty Details,neutral,neutral,"Agent: Hello, thank you for calling BrownBox C..."
16,Cancellations and returns,Replacement and Return Process,neutral,neutral,Agent: Thank you for reaching out to BrownBox ...
17,Warranty,Lost or Missing Warranty Card,neutral,neutral,"Agent: Hello, thank you for calling BrownBox c..."
18,Cancellations and returns,Return and Exchange,neutral,neutral,Agent: Thank you for calling BrownBox Customer...
19,Order,Order Confirmation and Status,neutral,neutral,Agent: Thank you for contacting BrownBox custo...

### Positive-class examples

In [29]:
positive_cases_df = test_results_df[test_results_df["true_label"] == "positive"].copy()
display(positive_cases_df[["issue_area", "issue_category", "true_label", "predicted_label", "is_correct", "conversation"]])

,issue_area,issue_category,true_label,predicted_label,is_correct,conversation
20,Order,Order Confirmation and Status,positive,neutral,False,Agent: Thank you for calling BrownBox Customer...
21,Order,Order Confirmation and Status,positive,neutral,False,Agent: Thank you for calling BrownBox Customer...
22,Order,Placing an Order,positive,neutral,False,Agent: Thank you for calling BrownBox customer...
23,Order,Placing an Order,positive,neutral,False,Agent: Thank you for calling BrownBox Customer...
24,Order,Order Confirmation and Status,positive,neutral,False,"Customer: Hi, I placed an order for a vacuum c..."
25,Order,Order Confirmation and Status,positive,neutral,False,"Customer: Hi, I'm calling to inquire about my ..."
26,Order,Placing an Order,positive,neutral,False,Agent: Thank you for calling BrownBox Customer...
27,Order,Product Information and Tags,positive,neutral,False,"Customer: Hi there, I'm interested in purchasi..."
28,Order,Order Confirmation and Status,positive,neutral,False,Agent: Thank you for calling BrownBox Customer...
29,Order,Product Information and Tags,positive,neutral,False,Agent: Thank you for calling BrownBox Customer...

### True vs predicted label counts

In [30]:
confusion_pairs = (
    test_results_df.groupby(["true_label", "predicted_label"])
    .size()
    .reset_index(name="count")
    .sort_values("count", ascending=False)
)
display(confusion_pairs)

  true_label predicted_label  count
4   positive         neutral     10
3    neutral         neutral      9
0   negative        negative      6
1   negative         neutral      4
2    neutral        negative      1

Identify which conversations were predicted correctly, which were misclassified, and where the model struggles most.